### ISSUE TITLE
What is program named "pup"?

### ISSUE THREAD

**Issue by emacs18** [lshprung/gnu-libc-dash-docset#1]
The documentation mentions something called "pup" to build the documentation.  I am unable to figure out what this program named pup is.  There is  no Debian package by that name.  Internet search for "pup" pops up "Potentially Unwanted Programs" mostly.

If this is part of some other package, can you tell me what the name of that package is?
Thanks.

**Comment by lshprung** [comment]
There is a Debian package by that name (as of Debian 11): https://tracker.debian.org/pkg/pup ([upstream](https://github.com/ericchiang/pup)). It is a tool similar to [jq](https://github.com/stedolan/jq) for parsing HTML. Perhaps I should add links to project homepages for each of the dependencies to make things more clear...

**Comment by emacs18** [comment]
I use Ubuntu 22.04.  There is no package named "pup".  

For now I just downloaded the binary from upstream.  The zip file I downloaded just had one executable named pup.
With this I was able to run the makefile to generate the doc.
Thanks.

As shown below, there is no package named `pup` on my Ubuntu.

    $ cat /etc/lsb-release
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=22.04
    DISTRIB_CODENAME=jammy
    DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
    
    $ sudo apt install pup
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    E: Unable to locate package pup
    $

So I downloaded [pup\_v0.4.0\_linux\_amd64.zip](https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip), unzipped then used it.
